<?php

require("game_table.inc");


/**
 * Implements hook_user_login
 */
function game_user_login(&$edit, $account) {
  if (!(!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset')) return;
  if (!array_search('Organizer', $account->roles)) return;

  module_load_include('module', 'am_tools', 'am_tools');
  $nid = am_get_game_nid();
  if ($nid == NULL) $GLOBALS['_GET']['destination'] = "node/add/game";
  else              $GLOBALS['_GET']['destination'] = "node/" . $nid;
}

/**
 * Implements hook_user_view_alter
 */
function game_node_view_alter(&$build) {

  if ($build['#bundle'] != 'game') return;
  drupal_alter('am_custom_game', $build);

  $build['game_table_form'] = drupal_get_form('_game_table_form');
  $build['game_page_time'] = game_page_time($build);
  $build['game_page_count'] = game_page_count($build);

  unset($build['field_time']);
}


/**
 * Implements hook_form_alter().
 */
function game_form_alter(&$form, $form_state, $form_id) {

	if ($form_id != 'game_node_form') return;
  if (isset($form['nid'])) return;
	
	global $user;
	if (!in_array('Organizer', $user->roles)) return;

	$start_time = $form['#entity']->field_time['und'][0]['value'];
	if ($start_time < time()) $form['field_time']['#disabled'] = true;
}

/**
 * Implements hook_node_insert().
 */
function game_node_insert($node) {
  if ($node->type == 'game') {
  // Set the countdown timer
    $end_time = strtotime($node->field_time['und'][0]['value2']);
    variable_set('jquery_countdown_timer_date', date('Y-m-d G:i:s', $end_time));

    global $user;
    if (!in_array('Organizer', $user->roles)) return;
    $GLOBALS['_GET']['destination'] = "node/add/game-rules";
  } 
  else if ($node->type == 'game-rules') {
    global $user;
    if (!in_array('Organizer', $user->roles)) return;

    module_load_include('module', 'am_tools', 'am_tools');
    $GLOBALS['_GET']['destination'] = "node/" . am_get_game_nid();
  }
}


function game_page_time($build) {

  $game = $build['#node'];
  $status = "na";

  $start_time = $game->field_time['und'][0]['value'];
  $end_time = $game->field_time['und'][0]['value2'];

  $start_time = strtotime($start_time);
  $end_time = strtotime($end_time);

  if ($end_time < time()) { 
    return $form['game_page_time'] = array(
                                            '#type' => 'item',
                                            '#title' => t('Game Time:'),
                                            '#markup' => 'Game is over.',
                                          );
  }

  ////////////////////////////////////////////////

  $duration = $end_time-$start_time;
  if ($duration > 604800) { // 1 Week
    $duration = $duration / 604800;
    $duration = round($duration) . ' week game - ';
  } 
  else { // Days
    $duration = $duration / 86400;
    $duration = round($duration) . ' day game - ';
  }

  if ($start_time > time()) {
    $interval = $start_time - time();
    if ($interval > 86400) { // 1 Day
      $time = $interval - 86400;
      $status = 'Game starts in ' . $time . ' days.';
    }
    else if ($interval > 3600) { // 1 Hour
      $status = 'Game starts in ' . date("H", $interval) . ' hours';
      if (date("i", $interval) > 0) $status = $status . ' and .' . date("i", $interval) . ' minutes';
      $status = $status . '.';
    }
    else if ($interval > 60) { // 1 Minute
      $status = 'Game starts in ' . date("i", $interval) . ' minutes.';
    }
    else {
      $status = 'Game starts in ' . date("s", $interval) . ' seconds.';
    }
  }
  else {
    $interval = $end_time - time();
    if ($interval > 86400) { // 1 Day
      $time = $interval / 86400;
      $status = floor($time) . ' days left in game.';
    }
    else if ($interval > 3600) { // 1 Hour
      $status = date("H", $interval) . ' hours';
      if (date("i", $interval) > 0) $status = $status . ' and .' . date("i", $interval) . ' minutes';
      $status = $status . ' left in game.';
    }
    else if ($interval > 60) { // 1 Minute
      $status = date("i", $interval) . ' minutes left in game.';
    }
    else {
      $status = date("s", $interval) . ' seconds left in game!';
    }
  }

  return $form['game_page_time'] = array(
                '#type' => 'item',
                '#title' => t('Game Time:'),
                '#markup' => $duration . $status,
            );
}

function game_page_count($build) {

	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
            ->fieldCondition('field_confirmed', 'value', 1)
	        ->entityCondition('bundle', 'kill')
	        ->propertyCondition('status', 1);

	$kills = $query->execute();

	////////////////////////////////////////////////

	return $form['game_page_count'] = array(
	            '#type' => 'item',
	            '#title' => t('Number of kills:'),
	            '#markup' => count($kills),
	        );
}