<?php

require('messaging_notifier.inc');
require('messaging_twilio.inc');

require('messaging_recipients.inc');
require('messaging_rule.inc');
require('messaging_read.inc');


function messaging_rules_action_info() {
	return array(
		'am_notifier' =>_create_notifier_action(),
		);
}


/*
 * Send message Notifier
 */
function messaging_send_to_notifier($message) {
	_messaging_am_notify($message);
}

/*
 * Send message API
 */
function _messaging_send_message($subject, $body, $to) {
	$node = new stdclass();
    $node->type = 'message';
    node_object_prepare($node);

    $node->language = 'und';

    $node->title = $subject;
    $node->field_body['und'][0]['value'] = $body;
    $node->field_body['und'][0]['safe_value'] = "<p>" . $body ."<p>";
    $node->field_body['und'][0]['format'] = 'filtered_html';

    $node->field_send_sms['und'][0]['value'] = 0;
    $node->field_send_email['und'][0]['value'] = 0;

    $node->field_recipients['und'] = $to;

    node_save($node);
}

function _messaging_get_organizers_uid() {
	$uids = array();

	$role_result = db_select('role', 'r')
					->fields('r', array('rid'))
				    ->condition('name', 'Organizer', '=')
				    ->range(0,1)
				    ->execute()
				    ->fetchAssoc();

	$rid = $role_result['rid'];

	$user_query = db_select('users_roles', 'ur');
	$user_query->fields('ur', array('uid'));
	$user_query->condition('rid', $rid, '=');
	$result = $user_query->execute();

	while($record = $result->fetchAssoc()) {
		array_push($uids, $record['uid']);
    }

	return $uids;
}

/*
function messaging_send_message_to_player($subject, $body, $to) {
	
    $recipients = "";
    _messaging_send_message($subject, $body, $from, $recipients);
}
*/

function messaging_send_message_to_organizers($subject, $body) {
	
    $recipients_uids = _messaging_get_organizers_uid();
    $recipients = array();
    foreach ($recipients_uids as $uid) {
    	array_push($recipients, array('target_id' => $uid));
    }
    _messaging_send_message($subject, $body, $recipients);
}

/*
 * Messaging Utilities
 */
function _get_recipients_msg($message) {
  $recipients = _get_recipients_uids($message);
  foreach ($recipients as $recipient) {
    array_push($recipients, array('target_id' => $recipient));
  }
  return $recipients;
}