<?php

/**
 * implements hook_rules_condition_info().
 */ 
 function messages_read_rules_condition_info() {
    return array(
        'messages_read_rules_condition_reply_viewed' => array(
            'group' => 'player messages',
            'label' => t('Message is viewed by recipient(s)'),
            'description' => t('Check to see if the current user is in the recipients of the original message node'),
            'arguments' => array(
                'comment' => array(
                    'type' => 'comment', 
                    'label' => t('the reply'),
                ),
            ),
            'module' => 'messages_read',
        ),
    );
}

// data function
function users_who_alread_read($comment) {
    $uids = array();
    foreach ($comment->field_read_by['und'] as $key => $value) {
        array_push($uids, $value['target_id']);
    }
    return $uids;
}
function orignal_recipients($comment) {
    $uids = array();

    $query = db_select('field_data_field_recipient_s_', 'fr')
        ->fields('fr', array('field_recipient_s__target_id'))
        ->condition('entity_id', $comment->nid)
        ->execute();

    while($record = $query->fetchassoc()) {
       array_push($uids, $record['field_recipient_s__target_id']);
    }

    return $uids;
}
// custom condition callback
function messages_read_rules_condition_reply_viewed($comment, $settings) {
    global $user;

    if ($user->uid == $comment->uid) return false;
    if (!isset($comment->field_read_by['und'])) return true;
    if (in_array($user->uid, users_who_alread_read($comment))) return false;
    if (in_array($user->uid, orignal_recipients($comment))) return true;

    return false;
}

/**
 * implements hook_rules_action_info().
 */
function messages_read_rules_action_info() {
    return array(
        'messages_read_action_viewed' => array(
            'group' => t('Player messages'),
            'label' => t('Player viewed the message reply'),
            'parameter' => array(
                'comment' => array(
                    'type' => 'comment', 
                    'label' => t('the reply'),
                ),
            ),
        ),
    );
}
function messages_read_action_viewed($comment) {
    global $user;

    if (!isset($comment->field_read_by['und'])) $comment->field_read_by['und'] = array();
    $comment->field_read_by['und'][]['target_id'] = $user->uid;
	
    comment_save($comment);
}