<?php

require('assassinations_kill_action.inc');
require('assassination_player_profile.page.inc');

function assassinations_rules_action_info() {
	return array(
		'am_kill' =>_create_kill_action(),
		);
}

function assassinations_user_view_alter(&$build) {
	//drupal_add_library('system', 'drupal.ajax');
  	//drupal_add_library('system', 'jquery.form');
  	//_assassinations_player_profile($build);
}

function assassinations_form_alter(&$form, &$form_state, $form_id) {

	$form['test'] = array(
                '#type' => 'button',
                '#name' => 'Test',
                '#value' => t('Test'),
                '#ajax'  => array(
					'callback' => 'assassinations_kill',
					'wrapper'  => 'the-wrapper-div-field',
					'method'   => 'replace',
					'effect'   => 'fade',
				),
            );

	return $form;
}

function assassinations_kill() {
	global $user;
	$user_id=$user->uid;
    watchdog("test", "Ajax test uid: " . $user_id);
}