<?php

function am_tools_field_val($field) {
	if (!isset($field['und'])) return "";
	return $field['und'][0]['value'];
}

function am_tools_user_name($user) {
	$name = am_tools_field_val($user->field_first_name);
	$name += " ";
	$name += am_tools_field_val($user->field_last_name);

	return $name;
}

function am_tools_valid($input) {
    if ($input == null) return false;
    if (!isset($input)) return false;

    return true;
}


function am_tools_organizer_uids() {
	$uids = array();

	$role_result = db_select('role', 'r')
					->fields('r', array('rid'))
				    ->condition('name', 'Organizer', '=')
				    ->range(0,1)
				    ->execute()
				    ->fetchAssoc();

	$rid = $role_result['rid'];

	$user_query = db_select('users_roles', 'ur');
	$user_query->fields('ur', array('uid'));
	$user_query->condition('rid', $rid, '=');
	$result = $user_query->execute();

	while($record = $result->fetchAssoc()) {
		array_push($uids, $record['uid']);
    }

	return $uids;
}