<?php
/**
 * @file
 * license_content_type.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function license_content_type_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-license_to_kill-field_license'
  $field_instances['node-license_to_kill-field_license'] = array(
    'bundle' => 'license_to_kill',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_license',
    'label' => 'License',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 8,
      ),
      'type' => 'text_textfield',
      'weight' => 31,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('License');

  return $field_instances;
}
