<?php

function message_players_form() {
    /* -- message form -- */
    $form['message_checkbox'] = array(
        '#type' => 'checkbox',
        '#title' => t('Message all players'),
    );

    $form['message'] = array(
        '#type' => 'container',
        '#states' => array(
            'visible' => array(
                ':input[name="message_checkbox"]' => array('checked' => true),
                ),
            ),
    );

    $form['message']['subject_field'] = array(
        '#type' => 'textfield',
        '#title' => t('subject:'),
        '#default_value' => '',
        '#size' => 30,
        '#maxlength' => 60,
    );

    $form['message']['email_checkbox'] = array(
        '#type' => 'checkbox',
        '#title' => t('Email them too'),
        '#default_value' => FALSE,
    );

    $form['message']['message_field'] = array(
        '#type' => 'textarea',
        '#title' => t('message'),
        '#wysiwyg' => false,
        '#rows' => 3,
    );

    $form['message']['message_send'] = array(
        '#type' => 'button', 
        '#name' => 'download',
        '#value' => t('send message'),
        '#button_type' => 'submit',
        '#executes_submit_callback' => true,
        '#submit' => array('send_message'),
    );

    return $form;
}

function message_to_all_form_validate(&$form, &$form_state) {
    if($form_state['values']['subject_field'] == "" || strlen($form_state['values']['subject_field']) == 0) {
        form_set_error('subject_field', t('must enter subject'));
    }
    if($form_state['values']['message_field'] == "" || strlen($form_state['values']['message_field']) == 0) {
        form_set_error('message_field', t('must enter message'));
    }
}

// form content manipulation
function get_user_ids() {

    $query = db_select('users', 'u')
        ->fields('u', array('uid'))
        ->condition('status', '1')
        ->execute();

    $uids = array();
    while($record = $query->fetch()) {
        $target_id = array ('target_id' => $record->uid);
        array_push($uids, $target_id);
    }

    return $uids;
}

function send_message(&$form, &$form_state) {
    $node = new stdclass();
    $node->type = 'message';
    node_object_prepare($node);

    $node->title = $form_state['values']['subject_field'];
    $node->field_message['und'][0]['value'] = $form_state['values']['message_field'];
    $node->field_message['und'][0]['format '] = 'filtered_html';

    $node->field_recipient_s_['und'] = get_user_ids();
    $node->field_send_email['und'][0]['value'] = $form_state['values']['email_checkbox'];

    node_save($node);
}