<?php

function player_ranking_cron() {
    $query = db_select('users', 'u')
            ->fields('u', array('uid'))
            ->condition('uid', array(0, 1), 'NOT IN');
    $query->addExpression('(SELECT COUNT(*) FROM field_data_field_killed_targets AS fk WHERE fk.entity_id = uid)', 'kills');
    $result = $query->execute();

    $usersKills = array();
    while($record = $result->fetchAssoc()) {
        $usersKills[$record['uid']] = $record['kills'];
    }

    if(count($usersKills) == 0) return;
    if(!arsort($usersKills)) return;

    $counter = 0;
    foreach ($usersKills as $key => $value) {
        $counter++;
        $user = user_load($key);
        $user->field_player_rank['und'][0]['value'] = $counter;
        user_save($user);
        unset($user);
    }
}